version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rafinha19
      MYSQL_DATABASE: figas
      MYSQL_USER: rafael
      MYSQL_PASSWORD: rafinha19
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - loja_network

  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/figas
      SPRING_DATASOURCE_USERNAME: rafael
      SPRING_DATASOURCE_PASSWORD: rafinha19
    depends_on:
      - db
    networks:
      - loja_network

networks:
  loja_network:
    driver: bridge

volumes:
  mysql-data:
